version: "3.7"
services:
  gogmc320:
    build: .
    user: root
    restart: unless-stopped
    volumes:
      - "./config.ini:/config.ini"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    logging:
      options:
        max-size: "30m"
    privileged: true
